### ISSUE TITLE
404

### ISSUE THREAD

**Issue by vlados** [DKunin/optimizilla-cli#1]
when I run 
`optimizilla output/page-0.png`
the result is :

> <!DOCTYPE html>
> <html>
>   <head><title>Page not found</title></head>
>   <style>
>       a img { border: 0 }
>       body { background-color: #caecf6 }
>       #noraptor {
>         left: 0%;
>         position: fixed;
>         top: 60%;
>       }
>       #notfound {
>         background: url(/mojo/notfound.png);
>         height: 62px;
>         left: 50%;
>         margin-left: -153px;
>         margin-top: -31px;
>         position:absolute;
>         top: 50%;
>         width: 306px;
>       }
>     </style>
>   <body>
>     <a href="http://optimizilla.com">
>       <img alt="Bye!" id="noraptor" src="/mojo/noraptor.png">
> </a>    <div id="notfound"></div>
>   </body>
> </html>
> 
> 
> 
> 
> 
>

**Comment by DKunin** [comment]
Sorry it took so long, just seen the issue!

Will look into it!

**Comment by DKunin** [comment]
Seems, it was either a one time thing, or last update fixed it, please check version 3.1.0.

**Comment by vlados** [comment]
Confirm that is working now
