### ISSUE TITLE
size image reducing very big

### ISSUE THREAD

**Issue by renanbastos93** [DKunin/optimizilla-cli#2]
It reduced too much the image that it was not possible to open it.

**Comment by DKunin** [comment]
Sorry it took so long, just seen the issue!

Will look into it!

**Comment by renanbastos93** [comment]
It's okay. If you need help, you can call me. We can fixed its bug together.

**Comment by DKunin** [comment]
@renanbastos93 I'm struggling with reproducing, can you provide an example image file, that caused trouble?

**Comment by renanbastos93** [comment]
@DKunin I don't remember, but I to know that it was more 10mb size the image. It was long time tha this occured. Also I do remember, that I did using Linux Fedora.

**Comment by DKunin** [comment]
@renanbastos93 Could you check again, please? Checked it with 10mb file, worked nicely on OSX.
<img width="605" alt="screen shot 2017-09-10 at 23 33 46" src="https://user-images.githubusercontent.com/996993/30252784-2d78ef64-9681-11e7-8e56-1b791764c9e2.png">

**Comment by renanbastos93** [comment]
Hey, I did many test and now was a success. This problem occurred the 3 month before. Probably already has some commit that fixed this bug.
Anything calls me.

**Comment by DKunin** [comment]
@renanbastos93 Thanks! If you find another error - open new issue, with examples of the problem.

Have a great day!
