### ISSUE TITLE
It don't receive image type tiff

### ISSUE THREAD

**Issue by renanbastos93** [DKunin/optimizilla-cli#3]
I try reduzing a image of the type tiff, but was not concluded!

![image](https://user-images.githubusercontent.com/8202898/30240949-8ac6fe22-9550-11e7-8626-8f854699ee0a.png)

**Comment by DKunin** [comment]
Will the same tiff work correctly with online UI?

**Comment by renanbastos93** [comment]
I don't testing with online UI, but let's testing now.

**Comment by renanbastos93** [comment]
I testing now on online UI, and not function !
![image](https://user-images.githubusercontent.com/8202898/30241006-9cfd9d66-9551-11e7-92b8-61774bae9dad.png)

**Comment by DKunin** [comment]
Ok, thanks - I will include warning that service can work only with jpeg or png, thanks!
