### ISSUE TITLE
Multiple File Upload

### ISSUE THREAD

**Issue by PixelCrux** [DKunin/optimizilla-cli#9]
The documentation mentions that uploading multiple files at once is possible. How is this done?

**Comment by DKunin** [comment]
![two-files](https://user-images.githubusercontent.com/996993/44005203-47cdd97e-9e78-11e8-8e87-83831f4ecba0.gif)
Simply run two or more files as arguments.

**Comment by PixelCrux** [comment]
So you have to manually type each file name? Is there no way to make this quicker? Perhaps I want to run the compressor on all of the images in a given folder.

**Comment by DKunin** [comment]
Not necessarily, you can use a mask like this:
`optimizilla ./folder/*.jpeg`

**Comment by PixelCrux** [comment]
I've tried that, but it throws "Error: form-data: ENOENT: no such file or directory" because it tries to reach it as an actual file named "*.jpeg"

**Comment by DKunin** [comment]
Strange....
Well you can try to work backwards, and feed the list of images like this:
`echo *.jpeg | xargs optimizilla`

So if you dryrun echo *.jpeg - you can verify,  that all files are present.

**Comment by PixelCrux** [comment]
No dice. The echo message just says, "*.jpeg"

**Comment by DKunin** [comment]
Ok, we're closer now, what kind of terminal are you using?
Are you using the command with quotes? The command should look exactly like, without any additional quotes:
`optimizilla ./folder/*.jpeg`

**Comment by PixelCrux** [comment]
I'm using the Node.js command prompt, seeing as this is an npm package. I'm not using any quotes.

**Comment by DKunin** [comment]
This is a cli tool, for now it can only be used as a terminal, or command line tool. You can fork the repo,  throw away all the cli code - and then you can use it as an npm module, and use it from node.

**Comment by PixelCrux** [comment]
I'm using the NPM CLI. I'm not trying to invoke the package from a JS file or anything.

**Comment by DKunin** [comment]
Can you show me the package.json you are running it from then? 
Or maybe a short gif of how you  are using it?

**Comment by PixelCrux** [comment]
![optimizilla test](https://user-images.githubusercontent.com/32367658/44006955-ce0c8e40-9e5a-11e8-97e0-0c1b0111d3a3.png)

**Comment by DKunin** [comment]
That sure sheds some light on the stuff, the problem is, that in Windows environment it doesn't recognize the *.jpeg as batch command.
Unfortunately I do not own a windows machine to testrun it, but my next guess will be, maybe to try ls command, making sure that there are only image files in the folder.

There is a chance that it still won't work - if the module doesn't escape the names of the folder - and since you have a space in the name - there could still be an error, but that's just a guess.

**Comment by PixelCrux** [comment]
![optimizilla test2](https://user-images.githubusercontent.com/32367658/44007130-20f011d8-9e5e-11e8-8afc-1ed4d1c3e400.png)

**Comment by DKunin** [comment]
No, unfortunately `dir` command wont't do. If there is no simple `ls` command that you can pipe into optimizilla - unfortunately there is nothing more I can help you with. Still the best way would be just to fork the code and debug it on your machine.

**Comment by PixelCrux** [comment]
Alright, too bad. Thanks for your help.

**Comment by marcorivm** [comment]
This works to pipe each file to the command from windows
```
 Get-ChildItem -Path ./ -Name | ForEach-Object { optimizilla $_ }
```
The downside is it will run the command once for each file, so no parallel upload.

This one works with parallel upload but creates a variable.
```
$imgList = Get-ChildItem -Path ./ ; optimizilla $imgList -d
```

And finally, it will throw a warning but process all items correctly
```
optimizilla `$(Get-ChildItem -Path ./ -Name -Include *.jpg,*.png,*.jpeg)` -d
```

I opened an Issue here https://github.com/sindresorhus/meow/issues/120 regarding piped arguments
